 const posts = [
  {
    id: 1,
    username: 'user1',
    imageUrl: 'https://via.placeholder.com/150',
    description: 'This is the description for post 1.',
    likes: 10,
    comments: 5,
  },
  {
    id: 2,
    username: 'user2',
    imageUrl: 'https://via.placeholder.com/150',
    description: 'This is the description for post 2.',
    likes: 15,
    comments: 7,
  },
  {
    id: 3,
    username: 'user3',
    imageUrl: 'https://via.placeholder.com/150',
    description: 'This is the description for post 3.',
    likes: 20,
    comments: 8,
  },
  {
    id: 4,
    username: 'user4',
    imageUrl: 'https://via.placeholder.com/150',
    description: 'This is the description for post 4.',
    likes: 25,
    comments: 10,
  },
  {
    id: 5,
    username: 'user5',
    imageUrl: 'https://via.placeholder.com/150',
    description: 'This is the description for post 5.',
    likes: 30,
    comments: 12,
  },
  {
    id: 6,
    username: 'user6',
    imageUrl: 'https://via.placeholder.com/150',
    description: 'This is the description for post 6.',
    likes: 35,
    comments: 15,
  },
  {
    id: 7,
    username: 'user7',
    imageUrl: 'https://via.placeholder.com/150',
    description: 'This is the description for post 7.',
    likes: 40,
    comments: 18,
  },
  {
    id: 8,
    username: 'user8',
    imageUrl: 'https://via.placeholder.com/150',
    description: 'This is the description for post 8.',
    likes: 45,
    comments: 20,
  },
  {
    id: 9,
    username: 'user9',
    imageUrl: 'https://via.placeholder.com/150',
    description: 'This is the description for post 9.',
    likes: 50,
    comments: 22,
  },
  {
    id: 10,
    username: 'user10',
    imageUrl: 'https://via.placeholder.com/150',
    description: 'This is the description for post 10.',
    likes: 55,
    comments: 25,
  },
  {
    id: 11,
    username: 'user11',
    imageUrl: 'https://via.placeholder.com/150',
    description: 'This is the description for post 11.',
    likes: 60,
    comments: 28,
  },
  {
    id: 12,
    username: 'user12',
    imageUrl: 'https://via.placeholder.com/150',
    description: 'This is the description for post 12.',
    likes: 65,
    comments: 30,
  },
  {
    id: 13,
    username: 'user13',
    imageUrl: 'https://via.placeholder.com/150',
    description: 'This is the description for post 13.',
    likes: 70,
    comments: 32,
  },
  {
    id: 14,
    username: 'user14',
    imageUrl: 'https://via.placeholder.com/150',
    description: 'This is the description for post 14.',
    likes: 75,
    comments: 35,
  },
  {
    id: 15,
    username: 'user15',
    imageUrl: 'https://via.placeholder.com/150',
    description: 'This is the description for post 15.',
    likes: 80,
    comments: 38,
  },
  {
    id: 16,
    username: 'user16',
    imageUrl: 'https://via.placeholder.com/150',
    description: 'This is the description for post 16.',
    likes: 85,
    comments: 40,
  },
  {
    id: 17,
    username: 'user17',
    imageUrl: 'https://via.placeholder.com/150',
    description: 'This is the description for post 17.',
    likes: 90,
    comments: 42,
  },
  {
    id: 18,
    username: 'user18',
    imageUrl: 'https://via.placeholder.com/150',
    description: 'This is the description for post 18.',
    likes: 95,
    comments: 45,
  },
  {
    id: 19,
    username: 'user19',
    imageUrl: 'https://via.placeholder.com/150',
    description: 'This is the description for post 19.',
    likes: 100,
    comments: 48,
  },
  {
    id: 20,
    username: 'user20',
    imageUrl: 'https://via.placeholder.com/150',
    description: 'This is the description for post 20.',
    likes: 105,
    comments: 50,
  },
];
export default posts;